services:
  # PHP 앱 개발 환경
  php-dev:
    build:
      context: ./php-app
    ports:
      - "8000:80"
    volumes:
      - ./php-app:/var/www/html
    environment:
      # PHP 코드에서 사용할 환경 변수 설정
      - ORACLE_HOST=oracle-dev
      - ORACLE_PASSWORD=your-oracle-password
    depends_on:
      # oracle-dev 서비스가 먼저 시작되도록 설정
      - oracle-dev

  # Oracle DB 개발 환경
  oracle-dev:
    image: gvenzl/oracle-free:latest
    ports:
      # (선택사항) DBeaver 같은 DB 툴로 접속하려면 주석 해제
      - "1521:1521"
    environment:
      # 컨테이너 생성 시 사용할 비밀번호 (위 php-dev와 일치시켜야 함)
      - ORACLE_PASSWORD=your-oracle-password
    volumes:
      # DB 데이터를 PC에 저장하여 컨테이너를 다시 켜도 데이터가 유지되도록 함
      - oracle-data:/opt/oracle/oradata

# Docker가 관리하는 명명된 볼륨(named volume)을 선언합니다.
# 이렇게 하면 'oracle-data'라는 이름의 데이터 저장 공간이 생성됩니다.
volumes:
  oracle-data:
